### ISSUE TITLE
input DNA without antibody as negative control with low sequencing depth 

### ISSUE THREAD

**Issue by icanwinwyz** [maxsonBraunLab/gopeaks#3]
Dear gopeaks developer,

Thanks for the software! My Cut&Tag experiment has two replicates per condition and uses input DNA without antibody as the negative control. Replicate 1 yielded 12.8M reads, replicate 2 yielded 10M reads, and the negative control only yielded 150K reads. We expected negative control yielded so few reads since there is nearly nothing in the library. However, I found all Cut&Tag experiments have a negative control with similar sequencing depth as target samples. So I am wondering, is that OK if I can use my negative control with such low sequencing depth to normalize my target sample data?

**Comment by gartician** [comment]
Hi @icanwinwyz, 

To re-iterate your problem, your control sample has much lower read depth (150K) than the target samples (10 - 12.8M). While I haven't encountered this exact issue, I would encourage you to try GoPeaks anyways because the normalization step does not depend on the total number of reads. GoPeaks uses counts-per-millions to normalize target to control, so it's the ratio between them that is fed into peak calling.
