### ISSUE TITLE
Regarding memory usage

### ISSUE THREAD

**Issue by mitian223** [maxsonBraunLab/gopeaks#5]
Is there any guidance about how much memory a broad peak calling will need? I tried the basic command on a bam file of ~10GB, but the 100GB of memory I requested doesn't seem to be enough:

TERM_MEMLIMIT: job killed after reaching LSF memory usage limit.
Exited with exit code 130.

Resource usage summary:

    CPU time :                                   4869.76 sec.
    Max Memory :                                 102163 MB
    Average Memory :                             29643.43 MB
    Total Requested Memory :                     100000.00 MB
    Delta Memory :                               -2163.00 MB
    Max Swap :                                   -
    Max Processes :                              4
    Max Threads :                                11
    Run time :                                   3129 sec.
    Turnaround time :                            4309 sec.

The bam file is based on mm10 reference, any idea of how much memory I should request?

Thank you~

**Comment by gartician** [comment]
Hi @mitian223,

Thank you for your input. A BAM file of 10GB is usually above what I use GoPeaks for since CUT&Tag files are relatively small, but I don't think a 10GB BAM file is impossible to process. May I ask if there is also a control/IgG sample that goes along with the BAM file? As of the current 1.0 version, GoPeaks can consume lots of memory. In fact, my most recent test shows that GoPeaks needs 17X more memory per GB of the input file. Luckily my 3GB file was processed in 27 minutes. This is a known problem with GoPeaks, but it can definitely be remedied in the future. 

Instead of rewriting GoPeaks for now, I would try the following to debug your job:
  * Try using > 17X fold memory request for every GB in the input file? e.g. 170GB memory for a 10GB BAM file.
  * Have you tried to downsample the data to 1GB and then call peaks? Samtools view with the -s option will help with this. This should assess if the file was made incorrectly (if applicable). 
  * Request even more cores e.g. 8.

**Comment by gartician** [comment]
Hi @mitian223,

Consider using [Summit](https://github.com/gartician/summit), an ultralight and fast version of GoPeaks that requires considerably less memory. Please let me know if this is helpful for your analysis!
